[輔音]
[Bilabial]	#1
[雙唇音]
b = "ㄅ"
p = "ㄆ"
m = "ㄇ"

[Labiodental]	#2
[齒齦音]
f = "ㄈ"

[Alveolar]	#3
[硬腭音]
d = "ㄉ"
t = "ㄊ"
n = "ㄋ"
l = "ㄌ"
z = "ㄗ"
c = "ㄘ"
s = "ㄙ"

[Velar]	#4
[軟腭音]
g = "ㄍ"
k = "ㄎ"

[Glottal]	#5
[聲門音]
h = "ㄏ"

[Alveolo-palatal]#6
[齦腭音]
j = "ㄐ"
q = "ㄑ"
x = "ㄒ"

[Retroflex]	#7
[捲舌音]
zh = "ㄓ"
ch = "ㄔ"
sh = "ㄕ"
r = "ㄖ"

[元音]
[Close-Front]	#8
[閉全前音]
i = "一"
yu = "ㄩ"

[Close-Back]	#9
[閉全後音]
u = "ㄨ"

[Open-Front]	#10
[開全前音]
a = "ㄚ"

[Close-mid-Back]#11
[閉半後音]
o = "ㄛ"

[Close-mid-Front]#12
[閉半前音]
e = "ㄜ"

[Open-mid-Front]#13
[開半前音]
e = "ㄝ"

[特殊音]
[Nasal]	#14, 15
[鼻音]
eng = "ㄥ" #14
en = "ㄣ"  #15

[R-colored]	#16
[日化元音]
er = "ㄦ"

[diphthong]
[雙元音]
#ㄞ -> \ㄚ\ + \ㄧ\ => ai
#ㄟ -> \ㄝ\ + \ㄧ\ => ei
#ㄠ -> \ㄚ\ + \ㄨ\ => ao
#ㄡ -> \ㄛ\ + \ㄨ\ => ou
[Vowel + Nasal]
[元音 + 鼻音]
#ㄢ -> \ㄚ\ + \ㄣ\ => an
#ㄤ -> \ㄚ\ + \ㄥ\ => ang
